"""Shared constants for feature diagram layout and rendering."""

MIN_BOX_W = 90
BOX_H = 45
H_SPACING = 60
V_SPACING = 140
PADDING = 40
MARKER_OFFSET = 8
MARKER_RADIUS = 6
TRIANGLE_H = 16
TRIANGLE_GAP = 8
TEXT_PADDING_X = 16
AVG_CHAR_W = 7
DEP_LANE_SPACING = 24
DEP_MARGIN = 30
DEP_ORTHO_OFFSET = 12
DEP_DASH = "5 4"
HUB_SPAN_THRESHOLD = 240.0

